# Generated by Django 4.0.3 on 2022-03-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SizeStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_bust', models.IntegerField()),
                ('st_waist', models.IntegerField()),
                ('st_girth', models.IntegerField()),
                ('st_sleeves', models.IntegerField()),
                ('international', models.CharField(max_length=45)),
                ('russian', models.IntegerField()),
                ('england', models.CharField(max_length=45)),
                ('usa', models.IntegerField()),
                ('europe', models.IntegerField()),
                ('italy', models.CharField(max_length=45)),
                ('japan', models.IntegerField()),
                ('footnote', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('login', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnthropometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bust', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('girth', models.IntegerField()),
                ('sleeves', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
