# Generated by Django 4.0.3 on 2022-03-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_sizestandard_footnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizestandard',
            old_name='st_girth',
            new_name='st_hips',
        ),
        migrations.RenameField(
            model_name='useranthropometry',
            old_name='girth',
            new_name='hips',
        ),
    ]
